/**
 * Sequoia: Database clustering technology.
 * Copyright (C) 2005 Continuent, Inc.
 * Contact: sequoia@continuent.org
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. 
 *
 * Initial developer(s): Emmanuel Cecchet.
 * Contributor(s): ______________________.
 */

package org.continuent.sequoia.driver;

import java.sql.SQLWarning;

/**
 * This class stores the result of a call to Statement.executeUpdate(sql,
 * Statement.RETURN_GENERATED_KEYS);
 * 
 * @author <a href="mailto:emmanuel.cecchet@continuent.com">Emmanuel Cecchet</a>
 * @version 1.0
 */
public class DriverGeneratedKeysResult
{
  private int             updateCount = 0;
  private DriverResultSet drs;
  private SQLWarning      statementWarnings;

  /**
   * Creates a new <code>DriverGeneratedKeysResult</code> object
   * 
   * @param drs the ControllerResultSet containing the autogenerated keys
   * @param updateCount the update count returned by the executeUpdate exection
   * @param sqlw SQL Warnings
   */
  public DriverGeneratedKeysResult(DriverResultSet drs, int updateCount,
      SQLWarning sqlw)
  {
    this.drs = drs;
    this.updateCount = updateCount;
    this.statementWarnings = sqlw;
  }

  /**
   * Returns the DriverResultSet value.
   * 
   * @return Returns the drs.
   */
  public final DriverResultSet getDriverResultSet()
  {
    return drs;
  }

  /**
   * Returns the updateCount value.
   * 
   * @return Returns the updateCount.
   */
  public final int getUpdateCount()
  {
    return updateCount;
  }

  /**
   * Returns the warnings value.
   * 
   * @return the updateCount warning chain.
   */
  public SQLWarning getWarnings()
  {
    return statementWarnings;
  }

}
